---
run:
  concurrency: 6
  timeout: 15m
issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - testableexamples
    - testifylint
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl
    - zerologlint
    # - cyclop
    # - depguard
    # - dupword
    # - err113
    # - exhaustruct
    # - forbidigo
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - inamedparam
    # - interfacebloat
    # - ireturn
    # - lll
    # - maintidx
    # - mnd
    # - nestif
    # - nilnil
    # - nonamedreturns
    # - paralleltest
    # - tagliatelle
    # - testpackage
    # - thelper
    # - varnamelen
    # - wrapcheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(k8s.io)
      - prefix(sigs.k8s.io)
      - localmodule
  revive:
    rules:
      - name: unused-parameter
        disabled: true
  gocyclo:
    min-complexity: 40
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  gocritic:
    enable-all: true
